global:
  name: Project Landscape
  short_name: Project
  repo: cfchase/starter-landscape
  website: 'https://landscape.project.org'
  short_domain: l.project.org
  company_url: 'https://project.org'
  email: info@project.foundation
  meta:
    title: Project Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@project'
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: Project Partner
  flags:
    cncf_sandbox: false
    companies: Project Partner
twitter:
  search: landscape.project.org
  url: 'https://landscape.project.org'
  text: Project Landscape
relation:
  label: Project Relation
  url: project
  values:
    - id: hosted
      label: Project Foundation Projects
      children:
        - id: foundationproject
          label: Project Foundation Projects
          prefix: Project
          tag: Foundation Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: Project Foundation Project
          big_picture_color: 'rgb(24,54,114)'
    - id: company
      label: Project Foundation Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: Project Foundation Member Products/Projects
      tag: Project Foundation Member
    - id: false
      label: Non-Project Foundation Member Products/Projects
      url: 'no'
membership:
  General:
    name: Project
    label: Member
    funding: General
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  'false':
    funding: 'No'
home:
  header: >
    <h1>Project Landscape</h1> The Project Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads: []
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Project Landscape
    fullscreen_header: See the interactive landscape at l.project.org
    method: getGroupedItemsForCncfBigPicture
    size:
      width: 1115
      height: 770
    fullscreen_size:
      width: 1155
      height: 840
    elements:
      - type: HorizontalCategory
        category: Project Partner
        rows: 6
        width: 730
        height: 200
        top: 570
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: LandscapeInfo
        width: 365
        height: 200
        top: 570
        left: 750
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the Project community, and also shows the member organizations of the Project Foundation.
            top: 45
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 40
            left: 5
            width: 90
            height: 90
          - type: title
            title: l.project.org
            top: 129
            left: 19
            font_size: 21
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 45
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 85
test:
  header: Project Landscape
  section: Project Foundation Members
  logo: twitter.svg
update_server:
  ip: 147.75.106.211
  update_hour: 0
  update_minute: 0
